### ISSUE TITLE
Message Dispatching Keyboard Accelerators

### ISSUE THREAD

**Issue by rombust** [dpjudas/UICore#12]
I am trying to implement a custom view that has a keyboard accelerator. So when 'A' is pressed, this event is procesed even though the view does not have focus.

There appears to be 3 options:
1) I could hook directly into the display window slot to do this, however the view may be hidden or disabled (i.e. not part of the view tree). 

2) Fire off the event on the root view in the ViewTree to cascade. However View::dispatch_event() dispatches messages at the target (and parent), not the child

3) Add a keyboard event slot on the ViewTree. The problem with this is when should the custom view connect the slot or disconnect the slot. i.e. If the View is unlinked from the ViewTree, the slot shouldn't be called. Then again, does all events have this same problem?

Any thoughts?

**Comment by dpjudas** [comment]
The simplest way of hooking a keyboard accelerator would be hooking the event on the root view. As the event dispatch bubbles upwards, if no view handled the keyboard event, the handler at the root gets its chance to do so.

In pseudo code:

``` c++
void MyView::hook_accelerators()
{
    slots.connect(root_view()->sig_key_press(), [this](auto event) {
        if (event->key() == Key::a && event->ctrl_down()) {
                e->stop_propagation();
                select_all();
        }
    });
}
```

Unfortunately there is no callback on View right now that tells a view when it is hooked up to a ViewTree, so it is a bit tricky to know when to call this hook_accelerators() function.

Perhaps a better way would be to create a KeyboardAccelerators class that hooks such global accelerators. Create that class in the root view where the accelerators thus work for any children of that view.

**Comment by rombust** [comment]
Many thanks.  This all makes sense.
