### ISSUE TITLE
View render border_box rounding

### ISSUE THREAD

**Issue by rombust** [dpjudas/UICore#18]
In https://github.com/dpjudas/UICore/blob/master/Sources/UICore/UI/View/view.cpp 
In Function: void ViewImpl::render(View *self, const CanvasPtr &canvas)
At Line 1061:
contains:
		Rect border_box = view->geometry().border_box();
Is this a typo, should we use Rectf instead of rect ?
		Rectf border_box = view->geometry().border_box();

**Comment by dpjudas** [comment]
Yes, I think that's a typo. It makes no sense to cast it to an integer and then back to a float.
