### ISSUE TITLE
Optimisation of StyleCascade

### ISSUE THREAD

**Issue by rombust** [dpjudas/UICore#19]
I have been experimenting in optimisation StyleCascade.

In my opinion, this is not required at the moment, unless like me, you have over 200 views which is unusual.

Simplified explanation:
I changed the StyleCascade property names to contain a hash value.
This has a nice side effect when obtaining properties that have index values: we can incorporate the index directly into the hash without requiring using the "integer to string" function overhead.

In my application, FPS increased from 138 to 192.

In addition, if I force the background renderer to use canvas.fill_rectangle() instead  of using path draw when an exact rectangle is drawn, then FPS increases to 273

**Comment by dpjudas** [comment]
Sounds interesting. Been wondering what would be the best way to deal with the property names being strings.

**Comment by dpjudas** [comment]
Closing this as I changed my mind about relying on CSS for layout. :)
